core/urls.py
from django.urls import path
from .views import (
    HomeView,
    OrderSummaryView,
    CheckoutView,
    ItemDetailView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    add_single_item_to_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    CategoryView,
    paypal_transaction,
    MyAccount,
    order_confirmation
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('category/<category>', CategoryView.as_view(), name='categories'),
    path('product/<slug>', ItemDetailView.as_view(), name='product'),
    path('order_summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('add_to_cart/<slug>', add_to_cart, name='add_to_cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove_from_cart/<slug>/<size>',
         remove_from_cart, name='remove_from_cart'),
    path('remove-item-from-cart/<slug>/<size>', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('add-item-to-cart/<slug>/<size>', add_single_item_to_cart,
         name='add-single-item-to-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('payment/paypal/capture-paypal-transaction/',
         paypal_transaction, name='paypalpayment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('myaccount/', MyAccount.as_view(), name='myaccount'),
    path('payment/<payment_option>/<order_ref_code>',
         order_confirmation, name='order_confirmation')


]

purplepond/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from cloudinary.models import CloudinaryField
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField
from django.contrib.postgres.fields import ArrayField
from multiselectfield import MultiSelectField
# Create your models here.
CATEGORY_CHOICES = (
    ('S', 'T-Shirt'),
    ('SW', 'Hoodies'),
    ('O', 'Polo Shirt')
)

LABEL_CHOICES = (
    ('primary', 'New'),
    ('secondary', 'Sale'),
    ('danger', 'Out of Stock'),
    ('success', 'Popular'),
    ('warning', 'Fast Selling'),

)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

SIZE_CHOICES = (
    ('XS', 'XS(36)'),
    ('S', 'S(38)'),
    ('M', 'M(40)'),
    ('L', 'L(42)'),
    ('XL', 'XL(44)'),
    ('XXL', 'XXL(46)'),
    ('XXXL', 'XXXL(48)'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=10)
    slug = models.SlugField()
    description = models.TextField()
    size = MultiSelectField(choices=SIZE_CHOICES)

    #image = models.ImageField()
    # Points to a Cloudinary image
    image = CloudinaryField('image')

    """ Informative name for model """

    def __unicode__(self):
        try:
            public_id = self.image.public_id
        except AttributeError:
            public_id = ''
        return "Item <%s:%s>" % (self.title, public_id)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add_to_cart", kwargs={
            'slug': self.slug,
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove_from_cart", kwargs={
            'slug': self.slug,
            'size': self.size
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered_size = models.CharField(max_length=4)
    ordereditem_title = models.CharField(max_length=100)
    ordereditem_price = models.FloatField(blank=True, null=True)
    ordereditem_totalprice = models.FloatField(blank=True, null=True)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    order_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)
    order_discount_amount = models.FloatField(blank=True, null=True)
    order_total = models.FloatField(blank=True, null=True)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user}'


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/home-page.html
{% extends 'base.html' %}
{% block content %}
{% load cloudinary %}

<!--Main layout-->
<main>

  <div class="container">

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">

          {% with url_path=request.get_full_path %}
          <li class="nav-item {% if url_path == '/' %}active{% endif %}">
            <a class="nav-link" href="/">All
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item {% if url_path == '/category/S' %}active{% endif %}">
            <a class="nav-link" href="/category/S">T-Shirts</a>
          </li>
          <li class="nav-item {% if url_path == '/category/SW' %}active{% endif %}">
            <a class="nav-link" href="/category/SW">Hoodies</a>
          </li>
          <li class="nav-item {% if url_path == '/category/O' %}active{% endif %}">
            <a class="nav-link" href="/category/O">Polo Shirts</a>
          </li>
          {% endwith %}
        </ul>
        <!-- Links -->

        <form class="form-inline">
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" name="q" placeholder="Search" aria-label="Search">
          </div>
        </form>
      </div>
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        {% for item in object_list %}
        <div class="col-lg-3 col-md-6 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card image-->
            <div class="view overlay">
              <!-- <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" -->
              <img src="{{item.image.url}}" class="card-img-top" alt="">

              <a href="{{item.get_absolute_url}}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>
            <!--Card image-->

            <!--Card content-->
            <div class="card-body text-center">
              <!--Category & Title-->
              <a href="{{item.get_absolute_url}}" class="grey-text">
                <h5>{{item.get_category_display}}</h5>
              </a>
              <h5>
                <strong>
                  <a href="{{item.get_absolute_url}}" class="dark-grey-text">{{item.title}}
                    <span class="badge badge-pill {{item.label}}-color">{{item.get_label_display}}</span>
                  </a>
                </strong>
              </h5>

              <h4 class="font-weight-bold blue-text">
                <strong>
                  {% if item.discount_price %}
                  £{{item.discount_price}}
                  {% else %}
                  £{{item.price}}
                  {% endif %}
                </strong>
              </h4>

            </div>
            <!--Card content-->

          </div>
          <!--Card-->

        </div>
        {% endfor %}
        <!--Grid column-->

      </div>
      <!--Grid row-->


    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->
    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        {% if  page_obj.has_previous %}
        <!--Arrow left-->
        <li class="page-item">
          <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}
        {% for page in page_obj.paginator.page_range %}
        {% if page == page_obj.number %}
        <li class="page-item active">
          <a class="page-link">{{page}}
            <span class="sr-only">(current)</span>
          </a>
        </li>
        {% else %}
        <li>
          <a class="page-link" href="?page={{page}}">{{page}}
          </a>
        </li>
        {% endif %}
        {% endfor %}
        {% if  page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}
    <!--Pagination-->

  </div>


</main>
<!--Main layout-->

{% endblock %}

templates/navbar.html
{% load cart_template_tags %}
<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

        <!-- Brand -->
        <a class="navbar-brand waves-effect" href="/">
            <h1 class="purple-text" style="font-family:Comic sans MS;font-size:24px">PurplePond</h1>
        </a>

        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left -->
            <ul class="navbar-nav mr-auto">
                {% comment %} <li class="nav-item active">
                    <a class="nav-link waves-effect" href="/">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="checkout">Checkout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="product">Products</a>
                </li> {% endcomment %}
            </ul>

            <!-- Right -->
            <ul class="navbar-nav nav-flex-icons">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
                        <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
                        <em class="fas fa-shopping-cart"></em>
                        <span class="clearfix d-sm-inline-block"> Cart </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'core:myaccount'%}">
                        <span class="clearfix d-sm-inline-block"> Account </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'account_logout'%}">
                        <span class="clearfix d-sm-inline-block"> Logout </span>
                    </a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'account_login'%}">
                        <span class="clearfix d-sm-inline-block"> Login </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'account_signup'%}">
                        <span class="clearfix d-sm-inline-block"> SignUp </span>
                    </a>
                </li>
                {% endif %}
            </ul>

        </div>

    </div>
</nav>
<!-- Navbar -->

templates/order_snippet.html
            {% load cart_template_tags %}
            <!--Grid column-->
            <div class="col-md-12 mb-4">
                <!-- Heading -->
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-muted">Your cart</span>
                    <span class="badge badge-secondary badge-pill">{{request.user|cart_item_count}}</span>
                </h4>

                <!-- Cart -->
                <ul class="list-group mb-3 z-depth-1">
                    {% for order_item in order.items.all %}
                    <li class="list-group-item d-flex justify-content-between lh-condensed">
                        <div>
                            <h6 class="my-0">{{order_item.quantity}} x {{order_item.item.title}}</h6>
                            <small class="text-muted">Size - {{order_item.ordered_size}}</small>
                        </div>
                        <span class="text-muted">£{{order_item.get_final_price}}</span>
                    </li>
                    {% endfor %}
                    <li class="list-group-item d-flex justify-content-between lh-condensed">
                        <div>
                            <h6 class="my-0">Shipping Charge</h6>
                        </div>
                        <span class="text-muted">Free</span>
                    </li>
                    {% if order.coupon %}
                    <li class="list-group-item d-flex justify-content-between bg-light">
                        <div class="text-success">
                            <h6 class="my-0">Promo code</h6>
                            <small>{{order.coupon.code}}</small>
                        </div>
                        <span class="text-success">-£{{order.coupon.amount}}</span>
                    </li>
                    {% endif %}
                    <li class="list-group-item d-flex justify-content-between">
                        <span>Total (GBP)</span>
                        <strong>£{{order.get_total}}</strong>
                    </li>
                </ul>
                <!-- Cart -->
                <!-- Promo code -->
                {% if DISPLAY_COUPON_FORM %}
                <form class="card p-2" action="{% url 'core:add-coupon'%}" method="POST">
                {% csrf_token %}
                <div class="input-group">
                    {% comment %} <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username"
                    aria-describedby="basic-addon2"> {% endcomment %}
                    {{couponform.code}}
                    <div class="input-group-append">
                    <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
                    </div>
                </div>
                </form>
                {% endif %}
                <!-- Promo code -->
            </div>

templates/order_summary.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Size</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.ordered_size }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug order_item.ordered_size %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'core:add-single-item-to-cart' order_item.item.slug order_item.ordered_size %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                £{{ order_item.get_total_discount_item_price }}
                <span class="badge badge-primary"><i class='fas fa-coins mr-1'></i>£{{ order_item.get_amount_saved }}</span>
            {% else %}
                £{{ order_item.get_total_item_price }}
            {% endif %}
            <a style='color: red;' href="{% url 'core:remove_from_cart' order_item.item.slug order_item.ordered_size %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endfor %}
        {% if object.coupon %}
        <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td><b>-£{{ object.coupon.amount }}</b></td>
        </tr>
        {% endif %}
        {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>£{{ object.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2 custom_width' href='/checkout/'>Proceed to checkout</a>
            <a class='btn btn-primary float-right custom_width' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock content %}

templates/paypalpayment.html
{% extends "base.html" %}

{% block extra_head %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<style>

</style>
{% endblock extra_head %}

{% block content %}

<main>
    <div class="container wow fadeIn">

        <h2 class="my-5 h2 text-center">Payment</h2>

        <div class="row">

            <div class="col-md-6" style="float:none;margin:auto;">
                <!-- #<div class="card"> -->
                <form>

                    {% csrf_token %}
                    <!-- Set up a container element for the button -->

                    <div id="paypal-button-container" type=submit></div>

                </form>



            </div>

            {% include "order_snippet.html" %}

        </div>

    </div>
</main>

{% endblock content %}

{% block extra_scripts %}

<script
    src="https://www.paypal.com/sdk/js?client-id=ASNlzmbPmt2HsasN9bLQKspdcCaWOJushqa8C2qHsbMVbrM8tUoYZXGF11wOncd6mQeJw7eQAdHuZsGs&currency=GBP"></script>

<script>
    csrfmiddlewaretoken = '{{ csrf_token }}';
    var total = "{{order.get_total}}";

    // Render the PayPal button into #paypal-button-container
    paypal.Buttons({

        style: {
            color: 'blue',
            shape: 'pill',
            label: 'pay',
            height: 40
        },

        // Set up the transaction
        createOrder: function (data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: parseFloat(total).toFixed(2)//'0.01'
                    }
                }]
            });
        },

        // Finalize the transaction
        onApprove: function (data, actions) {
            // This function captures the funds from the transaction.
            return actions.order.capture().then(function (details) {
                submitData(data)
                // This function shows a transaction success message to your buyer.

            });
        }
    }).render('#paypal-button-container');

    function submitData(data) {
        fetch('capture-paypal-transaction/', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Accept': 'application/json',
                'X-CSRFToken': csrfmiddlewaretoken,
                'X-Requested-With': 'XMLHttpRequest'
            },
            body: JSON.stringify({ 'orderID': data.orderID })
        })
            .then((response) => response.json())
            .then((data) => {
                if (data['success']) {
                    order_ref_code = data["order_ref_code"]
                    console.log(order_ref_code)
                    //  block of code to be executed if the condition is true
                    window.location.href = ("{% url 'core:order_confirmation' 'paypal' '%s' %}", order_ref_code)

                } else {
                    //  block of code to be executed if the condition is false
                    window.location.href = "{% url 'core:payment' 'paypal' %}"
                }


            })

    }





</script>

{% endblock extra_scripts %}

templates/product-page.html
{% extends 'base.html' %}
{% block content %}
{% load cloudinary %}
<!--Main layout-->
<main>
  <div class="container dark-grey-text">

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">

          {% with url_path=request.get_full_path %}
          <li class="nav-item {% if url_path == '/' %}active{% endif %}">
            <a class="nav-link" href="/">All
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item {% if url_path == '/category/S' %}active{% endif %}">
            <a class="nav-link" href="/category/S">T-Shirts</a>
          </li>
          <li class="nav-item {% if url_path == '/category/SW' %}active{% endif %}">
            <a class="nav-link" href="/category/SW">Hoodies</a>
          </li>
          <li class="nav-item {% if url_path == '/category/O' %}active{% endif %}">
            <a class="nav-link" href="/category/O">Polo Shirts</a>
          </li>
          {% endwith %}
        </ul>
        <!-- Links -->
      </div>
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->
    <!--Grid row-->
    <div class="row wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <img src="{{item.image.url}}" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <!--Content-->
        <div class="p-4">

          <div class="mb-3">
            <h5>
              <a>
                <span class="badge badge-info mr-1">{{object.get_category_display}}</span>
                <span class="badge badge-pill {{object.label}}-color ml-1">{{object.get_label_display}}</span>
              </a>
            </h5>

          </div>

          <p class="lead">

            {% if object.discount_price %}
            <span class="mr-1">
              <del>£{{object.price}}</del>
            </span>
            <span>£{{object.discount_price}}</span>
            {% else %}
            <span>£{{object.price}}</span>
            {% endif %}
          </p>
          <div class="row">

            <form action="{{object.get_add_to_cart_url}}" method="post">
              {% csrf_token %}
              <select class="form-control border colorful-select dropdown-primary"
                style="width: auto !important; display: inline-block;" name="item_size" id="item_size" required>
                <option value="" disabled selected>Choose Size</option>
                {% for value, name in form.fields.item_size.choices %}

                {% if value in object.size %}
                <option value="{{value}}">{{name}}</option>
                {% else %}
                <option disabled="disabled">{{name}} - Sold Out</option>
                {% endif %}

                {% endfor %}
              </select>
              <strong><label class="ml-2" for="item_size">Size</label></strong>
              <button class="btn btn-primary" type="submit">Add to Cart<em
                  class="fa fa-shopping-cart ml-1"></em></button>
            </form>


          </div>
          <!--Content-->
          <div>
            <p class="lead font-weight-bold mt-2">Description</p>

            <p style="text-align: justify;">{{object.description}}</p>

          </div>
        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      {% comment %} <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div> {% endcomment %}
      <!--Grid row-->

    </div>
</main>
<!--Main layout-->
{% endblock %}